# Generated by Django 3.1.7 on 2021-07-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('op1', models.CharField(max_length=30)),
                ('op2', models.CharField(max_length=30)),
                ('op3', models.CharField(max_length=30)),
                ('op1c', models.IntegerField(default=0)),
                ('op2c', models.IntegerField(default=0)),
                ('op3c', models.IntegerField(default=0)),
            ],
        ),
    ]
